#!/bin/bash

SUCCESS=0
FAIL=0
COUNTER=0
DIFF_RES=""


declare -a extra=(
"-n for test_1_grep.txt"
"-n for test_0_grep.txt"
"-n for test_2_grep.txt"
"-n for test_3_grep.txt"
"-n for test_4_grep.txt"
"-n for test_5_grep.txt"
"-e for test_1_grep.txt"
"-e for test_0_grep.txt"
"-e for test_2_grep.txt"
"-e for test_3_grep.txt"
"-e for test_4_grep.txt"
"-e for test_5_grep.txt"
"-i for test_1_grep.txt"
"-i for test_0_grep.txt"
"-i for test_3_grep.txt"
"-i for test_4_grep.txt"
"-v for test_1_grep.txt"
"-v for test_0_grep.txt"
"-v for test_2_grep.txt"
"-v for test_3_grep.txt"
"-v for test_5_grep.txt"
"-c for test_1_grep.txt"
"-c for test_0_grep.txt"
"-c for test_2_grep.txt"
"-c for test_3_grep.txt"
"-c for test_4_grep.txt"
"-c for test_5_grep.txt"
"-l for test_1_grep.txt"
"-l for test_0_grep.txt"
"-l for test_3_grep.txt"
"-l for test_4_grep.txt"
"-l for test_5_grep.txt"
"-s for test_1_grep.txt"
"-s for test_0_grep.txt"
"-s for test_3_grep.txt"
"-s for test_4_grep.txt"
"-s for test_5_grep.txt"
"-h for test_1_grep.txt"
"-h for test_0_grep.txt"
"-h for test_2_grep.txt"
"-h for test_3_grep.txt"
"-h for test_4_grep.txt"
"-h for test_5_grep.txt"
"-o for test_1_grep.txt"
"-o for test_0_grep.txt"
"-o for test_2_grep.txt"
"-o for test_3_grep.txt"
"-o for test_4_grep.txt"
"-o for test_5_grep.txt"
"-e for test_0_grep.txt"
"-ce ^int test_1_grep.txt"
"-e ^int test_1_grep.txt"
"-vh = test_3_grep.txt"
"-ie INT test_5_grep.txt"
"-ech test_1_grep.txt"
"-e = -e out test_5_grep.txt"
"-iv int test_5_grep.txt"
"-ioh int test_5_grep.txt"
"-c -f test_3_grep.txt test_1_grep.txt "
"-l for test_1_grep.txt "
"-os int test_4_grep.txt"
"-e = -e out test_5_grep.txt" 
"-e ing -e as -e the -e not -e is test_5_grep.txt"
"-e ing -e as -e the -e not -e is test_4_grep.txt"
"-i -f test_3_grep.txt test_5_grep.txt"
"-ivh = test_3_grep.txt"
"-ech test_0_grep.txt"
"-ech test_2_grep.txt"
"-ech test_3_grep.txt"
"-ech test_4_grep.txt"
"-e ing -e as -e the -e not -e is test_3_grep.txt"
"-e ing -e as -e the -e not -e is test_2_grep.txt"
"-e ing -e as -e the -e not -e is test_1_grep.txt"
"-i -f test_0_grep.txt test_1_grep.txt"
"-i -f test_3_grep.txt test_4_grep.txt"
"-ie INT test_0_grep.txt"
"-ie INT test_1_grep.txt"
"-ie INT test_2_grep.txt"
"-ie INT test_3_grep.txt"
"-ie INT test_4_grep.txt"
"-oh int test_5_grep.txt"
"-oh int test_4_grep.txt"
"-oh int test_3_grep.txt"
"-oh int test_2_grep.txt"
"-oh int test_1_grep.txt"
"-on int test_1_grep.txt"
"-on int test_2_grep.txt"
"-on int test_3_grep.txt"
"-on int test_5_grep.txt"
"-vh = test_0_grep.txt"
"-vh = test_1_grep.txt"
"-vh = test_2_grep.txt"
"-vh = test_5_grep.txt"
"-ol int test_5_grep.txt"
"-ol int test_4_grep.txt"
"-ol int test_3_grep.txt"
"-ol int test_2_grep.txt"
"-ol int test_1_grep.txt"
"-ln int test_5_grep.txt"
"-nl int test_3_grep.txt"
"-nl int test_2_grep.txt"
"-nl int test_1_grep.txt"
"-nh for test_0_grep.txt"
"-nh for test_2_grep.txt"
"-nh for test_3_grep.txt"
"-nh for test_4_grep.txt"
"-nh for test_5_grep.txt"
"-ic INT test_0_grep.txt"
"-ic INT test_1_grep.txt"
"-ic INT test_2_grep.txt"
"-ic INT test_3_grep.txt"
"-ic INT test_4_grep.txt"
"-il INT test_0_grep.txt"
"-il INT test_1_grep.txt"
"-il INT test_2_grep.txt"
"-il INT test_3_grep.txt"
"-il INT test_4_grep.txt"
"-in INT test_0_grep.txt"
"-in INT test_1_grep.txt"
"-in INT test_2_grep.txt"
"-in INT test_3_grep.txt"
"-ih INT test_0_grep.txt"
"-ih INT test_1_grep.txt"
"-ih INT test_2_grep.txt"
"-ih INT test_3_grep.txt"
"-ih INT test_4_grep.txt"
"-ih INT test_0_grep.txt"
"-is INT test_1_grep.txt"
"-is INT test_2_grep.txt"
"-is INT test_3_grep.txt"
"-io INT test_0_grep.txt"
"-io INT test_1_grep.txt"
"-io INT test_2_grep.txt"
"-io INT test_3_grep.txt"
"-io INT test_4_grep.txt"
"-io INT test_0_grep.txt"
"-hc INT test_0_grep.txt"
"-hc INT test_1_grep.txt"
"-hc INT test_2_grep.txt"
"-hc INT test_3_grep.txt"
"-hc INT test_4_grep.txt"
"-hl INT test_0_grep.txt"
"-hl INT test_1_grep.txt"
"-hl INT test_2_grep.txt"
"-hl INT test_3_grep.txt"
"-hl INT test_4_grep.txt"
"-hn INT test_0_grep.txt"
"-hn INT test_1_grep.txt"
"-hn INT test_2_grep.txt"
"-hn INT test_3_grep.txt"
"-hh INT test_0_grep.txt"
"-hh INT test_1_grep.txt"
"-hh INT test_2_grep.txt"
"-hh INT test_3_grep.txt"
"-hh INT test_4_grep.txt"
"-hh INT test_0_grep.txt"
"-hs INT test_1_grep.txt"
"-hs INT test_2_grep.txt"
"-hs INT test_3_grep.txt"
"-ho INT test_0_grep.txt"
"-ho INT test_1_grep.txt"
"-ho INT test_2_grep.txt"
"-ho INT test_3_grep.txt"
"-ho INT test_4_grep.txt"
"-ho INT test_0_grep.txt"

"-lc INT test_0_grep.txt"
"-lc INT test_1_grep.txt"
"-lc INT test_2_grep.txt"
"-lc INT test_3_grep.txt"
"-lc INT test_4_grep.txt"
"-sl INT test_0_grep.txt"
"-nl INT test_1_grep.txt"
"-hn INT test_3_grep.txt"
"-hh INT test_0_grep.txt"
"-hh INT test_1_grep.txt"
"-hh INT test_2_grep.txt"
"-hh INT test_3_grep.txt"
"-hh INT test_4_grep.txt"
"-hh INT test_0_grep.txt"
"-hs INT test_1_grep.txt"
"-hs INT test_2_grep.txt"
"-hs INT test_3_grep.txt"
"-ho INT test_0_grep.txt"
"-ho INT test_1_grep.txt"
"-ho INT test_2_grep.txt"
"-ho INT test_3_grep.txt"
"-ho INT test_4_grep.txt"
"-ho INT test_0_grep.txt"
"-vl s test_0_grep.txt"
"-vl s test_4_grep.txt"
"-vls s test_5_grep.txt"
"-vlsi s test_5_grep.txt"
"-lsi s test_5_grep.txt"
"-lsi s test_4_grep.txt"
"-lsi s test_3_grep.txt"
"-lsi s test_2_grep.txt"
"-lsi s test_1_grep.txt"
"-lsi s test_0_grep.txt"
"-csi s test_5_grep.txt"
"-csi s test_4_grep.txt"
"-csi s test_3_grep.txt"
"-csi s test_2_grep.txt"
"-csi s test_1_grep.txt"
"-csi s test_0_grep.txt"
"-hls INT test_2_grep.txt"
"-hls INT test_3_grep.txt"
"-hls INT test_4_grep.txt"
"-hns INT test_0_grep.txt"
"-hns INT test_1_grep.txt"
"-hns INT test_2_grep.txt"
"-loi s test_5_grep.txt"
"-loi s test_4_grep.txt"
"-loi s test_3_grep.txt"
"-loi s test_2_grep.txt"
"-loi s test_1_grep.txt"
"-loi s test_0_grep.txt"
"-coi s test_5_grep.txt"
"-coi s test_4_grep.txt"
"-coi s test_3_grep.txt"
"-coi s test_2_grep.txt"
"-coi s test_1_grep.txt"
"-coi s test_0_grep.txt"
"-hos INT test_2_grep.txt"
"-hos INT test_3_grep.txt"
"-hos INT test_4_grep.txt"
"-hnos INT test_0_grep.txt"
"-hnsi INT test_1_grep.txt"
"-hnosi INT test_2_grep.txt"

"-loie s test_5_grep.txt"
"-loie s test_4_grep.txt"
"-loie s test_3_grep.txt"
"-loie s test_2_grep.txt"
"-loie s test_1_grep.txt"
"-loie s test_0_grep.txt"
"-coie s test_5_grep.txt"
"-coie s test_4_grep.txt"
"-coie s test_3_grep.txt"
"-coie s test_2_grep.txt"
"-coie s test_1_grep.txt"
"-coie s test_0_grep.txt"
"-hose INT test_2_grep.txt"
"-hose INT test_3_grep.txt"
"-hose INT test_4_grep.txt"
"-hnose INT test_0_grep.txt"
"-hnsie INT test_1_grep.txt"
"-hnosie INT test_2_grep.txt"
)

testing()
{
    t=$(echo $@ | sed "s/VAR/$var/")
    ./s21_grep $t > test_s21_grep.log
    grep $t > test_sys_grep.log
    DIFF_RES="$(diff -s test_s21_grep.log test_sys_grep.log)"
    (( COUNTER++ ))
    if [ "$DIFF_RES" == "Files test_s21_grep.log and test_sys_grep.log are identical" ]
    then
      (( SUCCESS++ ))
      echo "\033[31m$FAIL\033[0m/\033[32m$SUCCESS\033[0m/$COUNTER \033[32msuccess\033[0m grep $t"
    else
      (( FAIL++ ))
      echo "\033[31m$FAIL\033[0m/\033[32m$SUCCESS\033[0m/$COUNTER \033[31mfail\033[0m grep $t"
    fi
    rm test_s21_grep.log test_sys_grep.log
}

# специфические тесты
for i in "${extra[@]}"
do
    var="-"
    testing $i
done
